const form=document.getElementById('marketingForm'),steps=[...document.querySelectorAll('.step')],bar=document.getElementById('progressBar'),label=document.getElementById('progressLabel'),nameEl=document.getElementById('progressName'),next=document.getElementById('nextBtn'),prev=document.getElementById('prevBtn'),submit=document.getElementById('submitBtn'),names=['Solicitante','Demanda','Material','Veículo / oferta','Canais / referências','Conferência'];let current=0;
function progress(){bar.style.width=((current+1)/steps.length*100)+'%';label.textContent='Etapa '+(current+1)+' de '+steps.length;nameEl.textContent=names[current];prev.style.display=current?'block':'none';next.style.display=current<steps.length-1?'block':'none';submit.style.display=current===steps.length-1?'block':'none';window.scrollTo({top:0,behavior:'smooth'})}
function validate(){const fields=[...steps[current].querySelectorAll('input,select,textarea')].filter(x=>!x.disabled&&x.offsetParent!==null);for(const x of fields){if(!x.checkValidity()){x.reportValidity();return false}}if(current===2&&!document.querySelector('input[name="fi-checkbox-tipo_material[]"]:checked')){alert('Selecione pelo menos um tipo de material.');return false}if(current===4&&!document.querySelector('input[name="fi-checkbox-canais_divulgacao[]"]:checked')){alert('Selecione pelo menos um canal.');return false}if(current===5)summary();return true}
function go(n){if(n<0||n>=steps.length)return;steps[current].classList.remove('active');current=n;steps[current].classList.add('active');progress()}
next.onclick=()=>{if(validate())go(current+1)};prev.onclick=()=>go(current-1);
document.querySelectorAll('input[name="fi-radio-necessita_gravacao"]').forEach(r=>r.onchange=()=>document.getElementById('gravacaoExtra').classList.toggle('hidden',!document.getElementById('gravExterna').checked));
document.querySelectorAll('input[name="fi-radio-envolve_veiculo"]').forEach(r=>r.onchange=()=>document.getElementById('veiculoFields').classList.toggle('hidden',!document.getElementById('veiSim').checked));
document.querySelectorAll('input[name="fi-radio-possui_oferta"]').forEach(r=>r.onchange=()=>document.getElementById('ofertaFields').classList.toggle('hidden',!document.getElementById('ofertaSim').checked));
document.getElementById('telefone').oninput=function(){let v=this.value.replace(/\D/g,'').slice(0,11);if(v.length<=10)v=v.replace(/^(\d{2})(\d)/,'($1) $2').replace(/(\d{4})(\d)/,'$1-$2');else v=v.replace(/^(\d{2})(\d)/,'($1) $2').replace(/(\d{5})(\d)/,'$1-$2');this.value=v};
function selected(name){return [...document.querySelectorAll('input[name="'+name+'"]:checked')].map(x=>x.value).join(', ')||'—'}
function summary(){document.getElementById('summary').innerHTML='<strong>Solicitante:</strong> '+document.getElementById('gerente').value+'<br><strong>Campanha:</strong> '+document.getElementById('campanha').value+'<br><strong>Prazo:</strong> '+document.getElementById('dataEntrega').value+'<br><strong>Prioridade:</strong> '+selected('fi-radio-prioridade')+'<br><strong>Material:</strong> '+selected('fi-checkbox-tipo_material[]')+'<br><strong>Canais:</strong> '+selected('fi-checkbox-canais_divulgacao[]')}
form.onsubmit=e=>{if(!validate()){e.preventDefault();return}submit.disabled=true;submit.textContent='Enviando...';next.disabled=true;prev.disabled=true};progress();
