window.MARKETING_API_BASE = "https://oeste-marketing-api.interno-oeste.workers.dev";
const API_BASE=(window.MARKETING_API_BASE||'').replace(/\/$/,'');const DEMO=!API_BASE;const DEMO_PASSWORD='demo';let token=sessionStorage.getItem('marketing_panel_token')||'';let currentRole=sessionStorage.getItem('marketing_panel_role')||'';let records=[];let selectedId=null;let rejectId=null;
const $=s=>document.querySelector(s),loginView=$('#loginView'),appView=$('#appView'),list=$('#requestList'),rejectModal=$('#rejectModal');
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function val(blocks,...keys){for(const k of keys){const v=blocks?.[k];if(v!==undefined&&v!==null&&v!=='')return Array.isArray(v)?v.join(', '):typeof v==='object'?JSON.stringify(v):String(v)}return ''}
function normalize(s){const b=s.blocks||{};const status=s.panelStatus||'pending';return{id:s.id,date:s.submissionDate||s.date||'',status,concessionaria:val(b,'fi-select-concessionaria','concessionaria'),solicitante:val(b,'fi-text-nome_solicitante','nome_solicitante')||val(b.sender,'fullName'),email:val(b,'fi-email-email_retorno','email_retorno')||val(b.sender,'email'),phone:val(b,'fi-phone-telefone','telefone')||val(b.sender,'phone'),campaign:val(b,'fi-text-nome_campanha','nome_campanha')||'Sem campanha',description:val(b,'fi-text-descricao_demanda','descricao_demanda'),objective:val(b,'fi-text-objetivo','objetivo'),deadline:val(b,'fi-date-data_entrega','data_entrega'),priority:val(b,'fi-radio-prioridade','prioridade')||'Normal',material:val(b,'fi-checkbox-tipo_material[]','tipo_material'),channels:val(b,'fi-checkbox-canais_divulgacao[]','canais_divulgacao'),vehicle:val(b,'fi-select-modelo_veiculo','modelo_veiculo'),version:val(b,'fi-text-versao_veiculo','versao_veiculo'),year:val(b,'fi-text-ano_modelo','ano_modelo'),offer:val(b,'fi-radio-possui_oferta','possui_oferta'),price:val(b,'fi-text-preco_vista','preco_vista'),notes:val(b,'fi-text-observacoes_finais','observacoes_finais'),gravacao:val(b,'fi-radio-necessita_gravacao','necessita_gravacao'),localGravacao:val(b,'fi-text-local_gravacao','local_gravacao'),dataGravacao:val(b,'fi-date-data_gravacao','data_gravacao'),horarioGravacao:val(b,'fi-text-horario_gravacao','horario_gravacao'),observacaoGravacao:val(b,'fi-text-observacoes_gravacao','observacoes_gravacao'),entrada:val(b,'fi-text-valor_entrada','valor_entrada'),parcelas:val(b,'fi-number-numero_parcelas','numero_parcelas'),valorParcela:val(b,'fi-text-valor_parcela','valor_parcela'),juros:val(b,'fi-text-taxa_juros','taxa_juros'),cet:val(b,'fi-text-cet','cet'),financiado:val(b,'fi-text-valor_financiado','valor_financiado'),financeira:val(b,'fi-text-instituicao_financeira','instituicao_financeira'),validadeOferta:val(b,'fi-date-validade_oferta','validade_oferta'),textoJuridico:val(b,'fi-text-texto_juridico','texto_juridico'),observacoesOferta:val(b,'fi-text-observacoes_oferta','observacoes_oferta'),linkReferencia:val(b,'fi-url-link_referencia','link_referencia'),descricaoReferencia:val(b,'fi-text-descricao_referencia','descricao_referencia'),files:s.files||[],driveUrl:s.driveUrl||''}}
function statusLabel(s){return({pending:'Pendente',in_review:'Em análise',approved:'Aprovada',rejected:'Reprovada',done:'Concluída'})[s]||s}
function badge(s){return '<span class="badge '+({pending:'b-pending',in_review:'b-review',approved:'b-approved',rejected:'b-rejected',done:'b-done'}[s]||'b-pending')+'">'+esc(statusLabel(s))+'</span>'}
function renderStats(){const c=s=>records.filter(r=>r.status===s).length;$('#statTotal').textContent=records.length;$('#statPending').textContent=c('pending');$('#statReview').textContent=c('in_review');$('#statApproved').textContent=c('approved');$('#statRejected').textContent=c('rejected')}
function renderList(){const q=$('#search').value.toLowerCase().trim(),sf=$('#statusFilter').value,pf=$('#priorityFilter').value;const filtered=records.filter(r=>(!q||[r.campaign,r.concessionaria,r.solicitante,r.email,r.id].join(' ').toLowerCase().includes(q))&&(!sf||r.status===sf)&&(!pf||r.priority===pf));$('#resultCount').textContent=filtered.length;if(!filtered.length){list.innerHTML='<div class="loading">Nenhuma solicitação encontrada.</div>';return}list.innerHTML=filtered.map(r=>'<article class="request '+(r.id===selectedId?'active':'')+'" data-id="'+esc(r.id)+'"><div class="request-top"><div class="request-title">'+esc(r.campaign)+'</div>'+badge(r.status)+'</div><div class="request-meta">'+esc(r.concessionaria)+' · '+esc(r.solicitante)+' · prazo '+esc(r.deadline||'não informado')+' · '+esc(r.priority)+'</div></article>').join('');list.querySelectorAll('.request').forEach(x=>x.onclick=()=>selectRecord(x.dataset.id))}
function field(label,value,full=false){return '<div class="detail-field '+(full?'full':'')+'"><div class="detail-label">'+esc(label)+'</div><div class="detail-value">'+esc(value||'—')+'</div></div>'}
function renderDetail(r){
  if(!r){$('#detail').innerHTML='<div class="empty-detail">Selecione uma solicitação para visualizar os detalhes.</div>';return}
  const fileHtml=(r.files||[]).map(f=>{const u=typeof f==='string'?f:(f?.url||'');return u?'<a href="'+esc(u)+'" target="_blank" rel="noopener">'+esc(u)+'</a>':''}).filter(Boolean).join('')||'<span class="detail-value">Nenhum arquivo informado.</span>';
  const driveHtml=currentRole==='marketing'
    ? '<div class="detail-section drive-section"><div class="drive-head"><div><h3>Materiais da demanda</h3><div class="drive-help">Cole o link da pasta do Google Drive onde os materiais finais estão disponíveis.</div></div><button id="driveHelpBtn" class="btn ghost drive-help-btn" type="button">Como funciona?</button></div><div class="drive-row"><input id="driveUrl" type="url" value="'+esc(r.driveUrl)+'" placeholder="https://drive.google.com/drive/folders/..." autocomplete="off"><button id="saveDriveBtn" class="btn primary" type="button">Salvar link</button></div><div id="driveMessage" class="drive-message"></div>'+(r.driveUrl?'<a class="drive-open" href="'+esc(r.driveUrl)+'" target="_blank" rel="noopener">📁 Abrir pasta no Google Drive</a>':'<div class="drive-empty">Nenhum link de materiais cadastrado.</div>')+'</div>'
    : (r.driveUrl?'<div class="detail-section drive-section"><h3>Materiais da demanda</h3><a class="drive-open" href="'+esc(r.driveUrl)+'" target="_blank" rel="noopener">📁 Abrir pasta no Google Drive</a></div>':'');
  const statuses=currentRole==='marketing'?['in_review','done']:['in_review','approved','rejected'];
  $('#detail').innerHTML='<div class="detail-topline"><div>'+badge(r.status)+'</div><button id="deleteRequestBtn" class="btn danger-outline" type="button">Excluir do painel</button></div><h2 class="detail-title">'+esc(r.campaign)+'</h2><div class="detail-sub">ID '+esc(r.id)+' · '+esc(r.date)+'</div><div class="detail-grid">'+field('Concessionária',r.concessionaria)+field('Solicitante',r.solicitante)+field('Prazo',r.deadline)+field('E-mail',r.email)+field('Telefone',r.phone)+field('Prioridade',r.priority)+field('Material',r.material)+field('Canais',r.channels)+field('Veículo',r.vehicle)+field('Versão / ano',[r.version,r.year].filter(Boolean).join(' · '))+field('Condição comercial',r.offer)+field('Preço à vista',r.price)+field('Entrada',r.entrada)+field('Parcelas',r.parcelas)+field('Valor da parcela',r.valorParcela)+field('Taxa de juros',r.juros)+field('CET',r.cet)+field('Valor financiado',r.financiado)+field('Banco / financeira',r.financeira)+field('Validade da oferta',r.validadeOferta)+field('Necessita gravação',r.gravacao)+field('Local da gravação',r.localGravacao)+field('Data da gravação',r.dataGravacao)+field('Horário da gravação',r.horarioGravacao)+field('Observações da gravação',r.observacaoGravacao,true)+field('Texto jurídico/comercial',r.textoJuridico,true)+field('Observações da oferta',r.observacoesOferta,true)+field('Objetivo',r.objective,true)+field('Descrição da demanda',r.description,true)+field('Observações finais',r.notes,true)+'</div>'+driveHtml+'<div class="detail-section"><h3>Status da solicitação</h3><div class="status-actions">'+statuses.map(s=>'<button class="'+(r.status===s?'selected':'')+'" data-status="'+s+'">'+statusLabel(s)+'</button>').join('')+'</div></div><div class="detail-section reference-section"><h3>Referências enviadas pelo solicitante</h3><div class="reference-grid">'+
(r.linkReferencia?'<div class="reference-link"><strong>Link de referência</strong><a href="'+esc(r.linkReferencia)+'" target="_blank" rel="noopener">'+esc(r.linkReferencia)+'</a></div>':'')+
(r.descricaoReferencia?field('Como utilizar a referência',r.descricaoReferencia,true):'')+
'</div>'+
'<div class="detail-section files"><h3>Arquivos anexados pelo solicitante</h3>'+fileHtml+'</div></div>';
  bindDetailActions(r);
}
async function deleteRequest(id){
  const r=records.find(x=>x.id===id);
  if(!r)return;
  const ok=window.confirm('Excluir esta solicitação apenas do painel?\n\nEla continuará existindo no Forminit e poderá ser apagada separadamente por lá.');
  if(!ok)return;
  try{
    await api('/api/delete',{method:'POST',body:JSON.stringify({id})});
    selectedId=null;
    await load();
    $('#detail').innerHTML='<div class="empty-detail">Solicitação removida do painel.</div>';
  }catch(e){
    window.alert(e.message||'Não foi possível excluir a solicitação do painel.');
  }
}
async function api(path,options={}){const res=await fetch(API_BASE+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),...(token?{Authorization:'Bearer '+token}:{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||'Erro de comunicação com o painel');return data}
async function login(username,password){if(DEMO){if(password!==DEMO_PASSWORD)throw new Error('Modo demonstração: use a senha demo.');token='demo';currentRole='marketing';sessionStorage.setItem('marketing_panel_token',token);sessionStorage.setItem('marketing_panel_role',currentRole);return}const d=await api('/api/login',{method:'POST',body:JSON.stringify({username,password})});token=d.token;currentRole=d.role||'';sessionStorage.setItem('marketing_panel_token',token);sessionStorage.setItem('marketing_panel_role',currentRole)}
async function load(){if(DEMO){records=[{id:'demo-001',date:'07/10/2026 15:24',panelStatus:'pending',blocks:{'fi-select-gerente':'João Ricardo','fi-email-email_retorno':'rodrigo@oesteveiculos.com.br','fi-phone-telefone':'+5565981179528','fi-text-nome_campanha':'Teste de campanha','fi-text-descricao_demanda':'Exemplo de solicitação para demonstração do painel.','fi-text-objetivo':'Divulgar uma condição comercial.','fi-date-data_entrega':'12/10/2026','fi-radio-prioridade':'Normal','fi-checkbox-tipo_material[]':['Imagem'],'fi-checkbox-canais_divulgacao[]':['Instagram Feed','Instagram Stories'],'fi-select-modelo_veiculo':'Tracker','fi-text-versao_veiculo':'Premier','fi-text-ano_modelo':'2026/2026','fi-radio-possui_oferta':'Não'}}];$('#modeNotice').classList.remove('hidden');$('#modeNotice').innerHTML='<strong>Modo demonstração.</strong> A interface está publicada, mas ainda não está conectada ao Forminit. Para ativar os dados reais, será necessário configurar o backend seguro descrito no repositório.';}else{const d=await api('/api/submissions');records=(d.submissions||[]).map(normalize)}renderStats();renderList();if(selectedId){renderDetail(records.find(r=>r.id===selectedId))}}
function openRejectModal(id){const r=records.find(x=>x.id===id);if(!r)return;rejectId=id;$('#rejectCampaign').textContent=r.campaign+' — '+r.concessionaria+' — '+r.solicitante;$('#directorName').value='';$('#rejectMessage').value='';$('#rejectError').classList.add('hidden');rejectModal.classList.remove('hidden');setTimeout(()=>$('#directorName').focus(),0)}
function closeRejectModal(){rejectId=null;rejectModal.classList.add('hidden')}
async function confirmReject(){const name=$('#directorName').value.trim(),message=$('#rejectMessage').value.trim();$('#rejectError').classList.add('hidden');if(!name||!message){$('#rejectError').textContent='Informe o nome do diretor e a mensagem de reprovação.';$('#rejectError').classList.remove('hidden');return}const id=rejectId;try{await updateStatus(id,'rejected',{directorName:name,note:message});closeRejectModal()}catch(e){$('#rejectError').textContent=e.message;$('#rejectError').classList.remove('hidden')}}
function bindDetailActions(r){$('#detail').querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>b.dataset.status==='rejected'?openRejectModal(r.id):updateStatus(r.id,b.dataset.status));const del=$('#deleteRequestBtn');if(del)del.onclick=()=>deleteRequest(r.id);const save=$('#saveDriveBtn');if(save)save.onclick=()=>saveDriveUrl(r.id);const help=$('#driveHelpBtn');if(help)help.onclick=()=>$('#driveHelp').classList.remove('hidden')}
async function saveDriveUrl(id){const input=$('#driveUrl'),message=$('#driveMessage');const value=input.value.trim();message.className='drive-message';message.textContent='';try{const r=records.find(x=>x.id===id);if(!r)return;if(value){const u=new URL(value);if(!['drive.google.com','docs.google.com'].includes(u.hostname))throw new Error('Informe um link válido do Google Drive.')}await api('/api/drive',{method:'POST',body:JSON.stringify({id,driveUrl:value})});r.driveUrl=value;renderDetail(r)}catch(e){message.textContent=e.message;message.classList.add('error-msg')}}
async function updateStatus(id,status,extra={}){if(status==='done'){const r=records.find(x=>x.id===id);if(!r?.driveUrl){const m=$('#driveMessage');if(m){m.textContent='Cole e salve o link do Google Drive antes de concluir a demanda.';m.className='drive-message error-msg'}return}}if(DEMO){const r=records.find(x=>x.id===id);if(r){r.status=status;renderStats();renderList();renderDetail(r)}return}try{await api('/api/status',{method:'POST',body:JSON.stringify({id,status,...extra,driveUrl:records.find(r=>r.id===id)?.driveUrl||''})});await load();selectRecord(id)}catch(e){throw e}}
function selectRecord(id){selectedId=id;renderList();renderDetail(records.find(r=>r.id===id))}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').classList.add('hidden');try{await login($('#username').value.trim(),$('#password').value);loginView.classList.add('hidden');appView.classList.remove('hidden');await load()}catch(err){$('#loginError').textContent=err.message;$('#loginError').classList.remove('hidden')}}
$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('marketing_panel_token');sessionStorage.removeItem('marketing_panel_role');location.reload()};$('#refreshBtn').onclick=()=>load();$('#search').oninput=renderList;$('#statusFilter').onchange=renderList;$('#priorityFilter').onchange=renderList;$('#rejectClose').onclick=closeRejectModal;$('#rejectCancel').onclick=closeRejectModal;$('#rejectConfirm').onclick=confirmReject;$('#driveHelpClose').onclick=()=>$('#driveHelp').classList.add('hidden');$('#driveHelpClose2').onclick=()=>$('#driveHelp').classList.add('hidden');$('#driveHelp').onclick=e=>{if(e.target===$('#driveHelp'))$('#driveHelp').classList.add('hidden')};rejectModal.onclick=e=>{if(e.target===rejectModal)closeRejectModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!rejectModal.classList.contains('hidden'))closeRejectModal()});
if(token&&!DEMO){loginView.classList.add('hidden');appView.classList.remove('hidden');load().catch(()=>{sessionStorage.removeItem('marketing_panel_token');location.reload()})}