const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':extra.origin||'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS'}});

function b64url(s){return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');return atob(s+'='.repeat((4-s.length%4)%4))}
async function sign(payload,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload));return b64url(String.fromCharCode(...new Uint8Array(sig)))}
async function makeToken(secret){const p=b64url(JSON.stringify({exp:Date.now()+8*60*60*1000}));return p+'.'+await sign(p,secret)}
async function validToken(req,env){const h=req.headers.get('Authorization')||'';if(!h.startsWith('Bearer '))return false;const [p,s]=h.slice(7).split('.');if(!p||!s)return false;try{const data=JSON.parse(unb64(p));if(data.exp<Date.now())return false;return (await sign(p,env.SESSION_SECRET))===s}catch{return false}}
async function formDataFromBlocks(s){const b=s.blocks||{};return{gerente:b['fi-select-gerente']||b.gerente,email:b['fi-email-email_retorno']||b.email,telefone:b['fi-phone-telefone']||b.telefone,campanha:b['fi-text-nome_campanha']||b.nome_campanha,descricao:b['fi-text-descricao_demanda']||b.descricao_demanda,objetivo:b['fi-text-objetivo']||b.objetivo,data_entrega:b['fi-date-data_entrega']||b.data_entrega,prioridade:b['fi-radio-prioridade']||b.prioridade,tipo_material:b['fi-checkbox-tipo_material[]']||b.tipo_material,canais:b['fi-checkbox-canais_divulgacao[]']||b.canais_divulgacao,modelo:b['fi-select-modelo_veiculo']||b.modelo_veiculo,versao:b['fi-text-versao_veiculo']||b.versao_veiculo,ano:b['fi-text-ano_modelo']||b.ano_modelo,oferta:b['fi-radio-possui_oferta']||b.possui_oferta}}
function cors(env){return env.PANEL_ORIGIN||'https://oestechevrolet.github.io'}
export default{async fetch(req,env){const origin=cors(env);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS'}});const url=new URL(req.url);
try{
 if(url.pathname==='/api/login'&&req.method==='POST'){const {password}=await req.json();if(!password||password!==env.PANEL_PASSWORD)return json({message:'Senha inválida.'},401,{origin});return json({token:await makeToken(env.SESSION_SECRET)},200,{origin})}
 if(!await validToken(req,env))return json({message:'Não autorizado.'},401,{origin});
 if(url.pathname==='/api/submissions'&&req.method==='GET'){const u=new URL('https://api.forminit.com/v1/forms/'+env.FORMINIT_FORM_ID);u.searchParams.set('size','100');u.searchParams.set('files','true');u.searchParams.set('timezone','America/Cuiaba');const fr=await fetch(u,{headers:{'X-API-Key':env.FORMINIT_API_KEY,'Accept':'application/json'}});const fd=await fr.json();if(!fr.ok)return json({message:fd.message||'Falha ao consultar Forminit.'},502,{origin});const subs=fd?.data?.submissions||[];const ids=subs.map(s=>s.id);let statuses={};if(ids.length){const q=await env.DB.prepare('SELECT submission_id,status,note FROM request_status WHERE submission_id IN ('+ids.map(()=>'?').join(',')+')').bind(...ids).all();for(const r of q.results||[])statuses[r.submission_id]=r}return json({submissions:subs.map(s=>({...s,panelStatus:statuses[s.id]?.status||'pending',panelNote:statuses[s.id]?.note||''})),pagination:fd.data.pagination||{}},200,{origin})}
 if(url.pathname==='/api/status'&&req.method==='POST'){const {id,status,note=''}=await req.json();const allowed=['pending','in_review','approved','rejected','done'];if(!id||!allowed.includes(status))return json({message:'Status inválido.'},400,{origin});await env.DB.prepare('INSERT INTO request_status(submission_id,status,note,updated_at) VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(submission_id) DO UPDATE SET status=excluded.status,note=excluded.note,updated_at=CURRENT_TIMESTAMP').bind(id,status,note).run();return json({ok:true},200,{origin})}
 return json({message:'Rota não encontrada.'},404,{origin})
}catch(e){return json({message:e?.message||'Erro interno.'},500,{origin})}}};